calibration_points:
- point_id: 1
  workspace_coordinates:
    x: 39.5
    y: 52.5
    z: 0.0
  pixel_coordinates:
    u: 92.0
    v: 85.0
- point_id: 2
  workspace_coordinates:
    x: 39.5
    y: 0.0
    z: 0.0
  pixel_coordinates:
    u: 330.0
    v: 73.0
- point_id: 3
  workspace_coordinates:
    x: 39.5
    y: -52.5
    z: 0.0
  pixel_coordinates:
    u: 576.0
    v: 75.0
- point_id: 4
  workspace_coordinates:
    x: 0.0
    y: 52.5
    z: 0.0
  pixel_coordinates:
    u: 62.0
    v: 245.0
- point_id: 5
  workspace_coordinates:
    x: 0.0
    y: 0.0
    z: 0.0
  pixel_coordinates:
    u: 327.0
    v: 244.0
- point_id: 6
  workspace_coordinates:
    x: 0.0
    y: -52.5
    z: 0.0
  pixel_coordinates:
    u: 604.0
    v: 244.0
- point_id: 7
  workspace_coordinates:
    x: -39.5
    y: 52.5
    z: 0.0
  pixel_coordinates:
    u: 40.0
    v: 443.0
- point_id: 8
  workspace_coordinates:
    x: -39.5
    y: 0.0
    z: 0.0
  pixel_coordinates:
    u: 326.0
    v: 453.0
- point_id: 9
  workspace_coordinates:
    x: -39.5
    y: -52.5
    z: 0.0
  pixel_coordinates:
    u: 625.0
    v: 445.0
